name: online clipboard
description: "A new Flutter project."
publish_to: 'web,playstore'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_database: ^11.3.5
  clipboard: ^0.1.3
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  intl: ^0.20.2
  flutter_slidable: ^4.0.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
