// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd3_crY195AkFyLNpl9vS5CeSgM18T6NY',
    appId: '1:269083735311:web:f80c30a050a490edaefa7a',
    messagingSenderId: '269083735311',
    projectId: 'myappon-1c4fd',
    authDomain: 'myappon-1c4fd.firebaseapp.com',
    databaseURL: 'https://myappon-1c4fd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myappon-1c4fd.firebasestorage.app',
    measurementId: 'G-L117LXMYEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN8_O1V6KrRulbtg_gDd4wU5abnvaR3eU',
    appId: '1:269083735311:android:d88d555936ba861eaefa7a',
    messagingSenderId: '269083735311',
    projectId: 'myappon-1c4fd',
    databaseURL: 'https://myappon-1c4fd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myappon-1c4fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdAA5xAAqcrLijxJIjJ6cMkJfP6E5ChcU',
    appId: '1:269083735311:ios:be0a6924cf58ae6aaefa7a',
    messagingSenderId: '269083735311',
    projectId: 'myappon-1c4fd',
    databaseURL: 'https://myappon-1c4fd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myappon-1c4fd.firebasestorage.app',
    iosBundleId: 'com.example.myappon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdAA5xAAqcrLijxJIjJ6cMkJfP6E5ChcU',
    appId: '1:269083735311:ios:be0a6924cf58ae6aaefa7a',
    messagingSenderId: '269083735311',
    projectId: 'myappon-1c4fd',
    databaseURL: 'https://myappon-1c4fd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myappon-1c4fd.firebasestorage.app',
    iosBundleId: 'com.example.myappon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd3_crY195AkFyLNpl9vS5CeSgM18T6NY',
    appId: '1:269083735311:web:b25a23d032fc4e9faefa7a',
    messagingSenderId: '269083735311',
    projectId: 'myappon-1c4fd',
    authDomain: 'myappon-1c4fd.firebaseapp.com',
    databaseURL: 'https://myappon-1c4fd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myappon-1c4fd.firebasestorage.app',
    measurementId: 'G-HESFGFYSB1',
  );

}